#+TITLE: Introduction to Qualitative Data Analysis with Taguette
#+AUTHOR: Scott Bailey

* Introduction to Qualitative Data Analysis with Taguette
** What is qualitative data analysis?

From Chapter 1 of the SAGE Handbook of Qualitative Analysis:

#+BEGIN_QUOTE
Qualitative data analysis is the classification and interpretation of linguistic (or visual) material to make statements about implicit and explicit dimensions and structures of meaning-making in the material and what is represented in it. Meaning-making can refer to subjective or social meanings. Qualitative data analysis also is applied to discover and describe issues in the field or structures and processes in routines and practices. Often, qualitative data analysis combines approaches of a rough analysis of the material (overviews, condensation, summaries) with approaches of a detailed analysis (elaboration of categories, hermeneutic interpretations or identified structures). The final aim is often to arrive at generalizable statements by comparing various materials or various texts or several cases.
#+END_QUOTE

** Comparison of software used for QDA

[[https://drive.google.com/file/d/1ueapi3Rb88T8-kpU4nE8IYQd-NA1HNFl/view?usp=sharing][Comparison of QDA software]], created by Mia Partlow.

Taguette supports PDFs, Word Docs (.docx), Text files (.txt), HTML, EPUB, MOBI, Open Documents (.odt), and Rich Text Files (.rtf). If you need to work with audio and video files, you really have to look at the more expensive, paid software.

If you also want to look quantitatively at your qualitative data, using crosstabs or complex matrix queries, or if you work on a team and want to do interrater reliability more easily, you should look at NVivo and similar software.

** Installing Taguette (or using the online version)

First, Taguette has a great [[https://www.taguette.org/getting-started.html][getting started guide]]. We're going to be roughly following it in our workshop, but I recommend referring to it as needed.

In the interest of saving time today, we're all going to use the online version of Taguette, so you will need to [[https://app.taguette.org/][sign-up for an account]]. If you really don't want to sign up for an account, go ahead with the install instructions below.

You can install Taguette on Windows, Mac, or Linux following the directions [[https://www.taguette.org/install.html][here]].

On MacOS, if you run into a warning that you can't open the app for security, then open Settings -> Security and Privacy, and click Open Anyway in the General tab.

** Creating a Project and loading documents into Taguette

Once you've logged into Taguette, we need to create a project to contain the various documents we'll work on, and their associated codes and codebook.

Click "Create a project" and fill out the name and description fields.

You'll then see the basic Project view, with a sidebar on the left of the window. "Project info" let's you change the name and description of the project, add collaborators, export your codebook, and delete the project. We won't talk much about collaborators, but if are working on the hosted version of Taguette, on their servers, you can add collaborators to a shared project, and manage their permissions. You can find more information on that [[https://www.taguette.org/getting-started.html#collabs][here]].

"Documents" let's you add documents and turn on the "backlight," which greys out non-coded text, making it easier to see the text you've coded.

Click "Add a document," and select the PDFs of your readings for this week. When you add a document, you can specify a name as well as a description. If you don't put in a name, it will default to the file name. You can edit this later as well, by clicking the "edit" button by the document title in the "Documents" tab. When you import documents, Taguette is pulling out the raw text from the document for display and use in the application. Especially if you work with PDFs, you might get some artifacts from page numbers or footers, which we'll see momentarily.

** Viewing and coding documents

Now that we've uploaded two documents, we'll start to look at our documents and do a bit of coding.

First, click on the Qualitative Researcher's Companion. Scroll through and see what happened to the PDf when it was converted to plain text by Taguette.

Now let's think about coding. Here's two related approaches to content based coding.

Thematic coding: "Thematic analysis is a data reduction and analysis strategy by which qualitative data are segmented, categorized, summarized, and reconstructed in a way that captures the important concepts within the data set...Thematic coding is the strategy by which data are segmented and categorized for thematic analysis." From the SAGE Encyclopedia of Qualitative Research Methods.

In vivo coding: "In vivo coding is the practice of assigning a label to a section of data, such as an interview transcript, using a word or short phrase taken from that section of the data. This entry describes this practice and some applications and problems associated with it." From the SAGE Encyclopedia of Qualitative Research Methods.

In the left sidebar, click "Highlights." Here is where we can create a "tag," a code, and also see all the text that we've highlighted with that tag. Taguette gives you one tag, "interesting," by default, but we'll want to add our own. You can also create "tags" as you work through the text and highlight. We'll do that first.

In the document, highlight some text. You should then see a small popup that says "new highlight." Click that and you'll see a list of existing tags and an option to "Create a tag." Go ahead and create a tag that either expresses the theme of the text you highlighted or uses a word from that text. You'll give the tag a name, and a description that expresses the meaning of that tag, potentially with criteria for why some text would be highlighted with that tag.

After you create the tag, make sure to mark the checkbox for it before hitting save in the dialog box.

We'll do a bit of practice with coding in a moment, but let's cover one more feature before we do. Taguette does support tag hierarchies, through separating the parent and child tags with a punctuation mark. For example, we could create a tag called "software" that would be our top level tag. We could then create tags like "software.taguette" and "software.nvivo" that are sub-tags, or child tags.

Take a few minutes now to highlight more text, including in the other document we uploaded. Feel free to add a few more tags as it makes sense. While you're at it, try turning on the "backlight" option under the "Documents" tab.

Now let's see what views Taguette provides for our codes. First, click the "Highlights" tab then the name of a tag you're interested in. You should see boxes or "cards" with the text you highlighted and assigned to the tag. In the top right of the window, you'll have a button that says "Export this view," with a small downward-pointing arrow. You can click that arrow to select an export format, then click the format to export this selection of texts. Try it now with PDF format.

These exports allow you to compile these coded slices of your collection to help in your research and writing.

** Building a codebook

With qualitative analysis, you often produce a careful created codebook that explains your codes. Taguette can generate a codebook for you from the names and descriptions of your tags.

Click "Project info" in the left sidebar. You can click the downward-pointing arrow to select a format for export. Try PDF for now. The QDC (XML) format that you see there is the Codebook Exchange Format that qualitative tools can use to transfer codes between software.

** Further Resources

- The SAGE Handbook of Qualitative Data Analysis: https://catalog.lib.ncsu.edu/catalog/NCSU4540303
- The SAGE Encyclopedia of Qualitative Research Methods:
  Go to https://catalog.lib.ncsu.edu/catalog/NCSU2759096 and once in SAGE Research Methods, search for qualitative research.
